//
//  ExerciseDatabase.swift
//  FitnessTracker
//
//  Created by Evan Cohen on 8/8/25.
//


// Services/ExerciseDatabase.swift
import Foundation

class ExerciseDatabase: ObservableObject {
    static let shared = ExerciseDatabase()
    
    @Published var exercises: [Exercise] = []
    
    private init() {
        loadExercises()
    }
    
    private func loadExercises() {
        exercises = [
            // Warm-up
            Exercise(
                name: "Jumping Jacks",
                category: .cardio,
                muscleGroups: [.legs, .shoulders, .core],
                equipment: .bodyweight,
                description: "A full-body dynamic warm-up exercise.",
                instructions: ["Stand with feet together and hands at your sides.", "Jump up while spreading your feet and bringing your hands overhead.", "Return to the starting position."],
                difficulty: .beginner,
                exerciseType: .warmup,
                targetMuscleGroup: .legs
            ),
            Exercise(name: "AB Workout", category: .strength, muscleGroups: [core], equipment: .bodyweight, description: "A bodyweight core exercise that strengthens the abdominal muscles.", instructions: ["Lie on your back with your knees bent and feet flat.", "Place your hands behind your head or crossed over your chest.", "Engage your core and lift your upper body off the floor, then slowly return to the start."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .core)
            Exercise(name: "Around the World", category: .strength, muscleGroups: [shoulders], equipment: .dumbbells, description: "An isolation exercise for the shoulders that works the deltoids through a circular motion.", instructions: ["Stand with a dumbbell in each hand, palms facing your thighs.", "Lift the dumbbells up and out to the sides in a wide arc until they meet overhead.", "Slowly reverse the motion to return to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .shoulders)
            Exercise(name: "Arnold Curls", category: .strength, muscleGroups: [biceps], equipment: .dumbbells, description: "A variation of the bicep curl that incorporates wrist rotation for a greater range of motion.", instructions: ["Stand with a dumbbell in each hand, palms facing your body.", "As you curl the weights up, rotate your wrists so your palms face forward at the top of the movement.", "Slowly lower the weights back down, rotating your wrists to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .biceps)
            Exercise(name: "Arnold Press", category: .strength, muscleGroups: [shoulders], equipment: .dumbbells, description: "A shoulder press variation that targets all three heads of the deltoid muscle.", instructions: ["Sit on a bench with a dumbbell in each hand, palms facing your body.", "Press the dumbbells overhead while simultaneously rotating your palms to face forward.", "Slowly reverse the motion to return to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .shoulders)
            Exercise(name: "Bent Over Deltoid Shrug", category: .strength, muscleGroups: [back, .shoulders], equipment: .dumbbells, description: "An isolation exercise for the rear deltoids and upper back.", instructions: ["Hold a dumbbell in each hand and hinge at your hips, keeping your back flat.", "Let the dumbbells hang straight down with palms facing each other.", "Shrug your shoulders up and back, squeezing your shoulder blades together."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .back)
            Exercise(name: "Bent Over Row", category: .strength, muscleGroups: [back, .biceps], equipment: .dumbbells, description: "A compound exercise that builds strength and thickness in the back.", instructions: ["Hold a dumbbell in each hand and hinge at your hips, keeping your back straight.", "Pull the dumbbells up toward your chest, squeezing your shoulder blades together.", "Slowly lower the dumbbells back to the starting position with control."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .back)
            Exercise(name: "Bent Over Row", category: .strength, muscleGroups: [back, .biceps], equipment: .barbell, description: "A fundamental compound lift for building a strong and muscular back.", instructions: ["Stand with feet shoulder-width apart, gripping the barbell with an overhand grip.", "Hinge at your hips, keeping your back straight, until your torso is at a 45-degree angle.", "Pull the barbell up to your abdomen, squeezing your shoulder blades together, then slowly lower it back down."], difficulty: .intermediate, exerciseType: .primary, targetMuscleGroup: .back)
            Exercise(name: "Bent Over Row - Underhand", category: .strength, muscleGroups: [back, .biceps], equipment: .barbell, description: "A variation of the bent over row that places more emphasis on the biceps and lats.", instructions: ["Stand with feet shoulder-width apart, gripping the barbell with an underhand grip.", "Hinge at your hips, keeping your back straight, until your torso is at a 45-degree angle.", "Pull the barbell up to your abdomen, squeezing your lats, then slowly lower it back down."], difficulty: .intermediate, exerciseType: .primary, targetMuscleGroup: .back)
            Exercise(name: "Bent Over Shrug", category: .strength, muscleGroups: [back], equipment: .barbell, description: "An exercise for targeting the traps and upper back while in a bent-over position.", instructions: ["Hinge at your hips to assume a bent-over position, holding a barbell with an overhand grip.", "Let the barbell hang down with arms straight.", "Shrug your shoulders up toward your ears, then slowly lower them back down."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .back)
            Exercise(name: "Bicep Curl", category: .strength, muscleGroups: [biceps], equipment: .barbell, description: "A classic isolation exercise for building bicep strength and size.", instructions: ["Stand with your feet shoulder-width apart, holding a barbell with an underhand grip.", "Keep your elbows at your sides and curl the barbell up toward your shoulders.", "Slowly lower the barbell back to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .biceps)
            Exercise(name: "Bicep Curl", category: .strength, muscleGroups: [biceps], equipment: .cable, description: "An isolation exercise for the biceps that provides constant tension throughout the movement.", instructions: ["Attach a bar to a low cable pulley and stand facing the machine.", "Hold the bar with an underhand grip, keeping your elbows locked at your sides.", "Curl the bar up toward your shoulders, then slowly lower it back to the start."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .biceps)
            Exercise(name: "Bicep Curl", category: .strength, muscleGroups: [biceps], equipment: .dumbbells, description: "A popular isolation exercise for building the biceps.", instructions: ["Stand or sit with a dumbbell in each hand, palms facing forward.", "Keep your elbows close to your torso and curl the weights up to shoulder level.", "Slowly lower the dumbbells back to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .biceps)
            Exercise(name: "Box Squat", category: .strength, muscleGroups: [legs, .glutes], equipment: .barbell, description: "A squat variation used to improve form, depth, and explosive power.", instructions: ["Set a box or bench behind you at the desired squat depth.", "Perform a squat, sitting down on the box before standing back up.", "Keep your back straight and chest up throughout the movement."], difficulty: .intermediate, exerciseType: .primary, targetMuscleGroup: .legs)
            Exercise(name: "Bulgarian Split Squat", category: .strength, muscleGroups: [legs, .glutes], equipment: .dumbbells, description: "A challenging unilateral exercise for strengthening the legs and glutes.", instructions: ["Stand with one foot on a bench behind you, holding a dumbbell in each hand.", "Lower your body by bending your front knee until your back knee is just above the floor.", "Drive through your front foot to return to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .legs)
            Exercise(name: "Cable Crunch", category: .strength, muscleGroups: [core], equipment: .cable, description: "An effective core exercise that allows for progressive overload.", instructions: ["Kneel facing a cable machine with a rope attached to a high pulley.", "Hold the rope handles and crunch your torso down toward the floor.", "Slowly return to the starting position, maintaining tension on your abs."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .core)
            Exercise(name: "Cable Leg Extensions", category: .strength, muscleGroups: [legs], equipment: .cable, description: "An exercise that isolates the quadriceps muscles using a cable machine.", instructions: ["Attach an ankle cuff to a low pulley and stand facing away from the machine.", "Extend one leg forward against the cable resistance.", "Slowly return your leg to the starting position and repeat for reps."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .legs)
            Exercise(name: "Cable Pull Through", category: .strength, muscleGroups: [glutes], equipment: .cable, description: "A glute and hamstring-focused exercise that mimics the hip hinge movement.", instructions: ["Stand facing away from a low cable pulley, holding the rope between your legs.", "Hinge at your hips, letting the rope pull your torso down.", "Drive your hips forward to stand back up, squeezing your glutes at the top."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .glutes)
            Exercise(name: "Cable Twist", category: .strength, muscleGroups: [core], equipment: .cable, description: "A core exercise that strengthens the obliques and improves rotational power.", instructions: ["Stand sideways to a cable machine, holding a handle at chest level.", "Rotate your torso away from the machine, keeping your arms straight.", "Slowly return to the starting position with control."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .core)
            Exercise(name: "Calf Press on Leg Press", category: .strength, muscleGroups: [calves], equipment: .machine, description: "A machine-based exercise to target the calf muscles.", instructions: ["Sit in a leg press machine and place the balls of your feet on the edge of the platform.", "Press the platform away by extending your ankles.", "Slowly return to the starting position, stretching your calves."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .calves)
            Exercise(name: "Chest Dip", category: .strength, muscleGroups: [chest, .triceps], equipment: .bodyweight, description: "A compound bodyweight exercise that builds strength in the chest, shoulders, and triceps.", instructions: ["Grip parallel bars and lift your body up.", "Lean forward and lower your body until your shoulders are below your elbows.", "Push back up to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .chest)
            Exercise(name: "Chest Fly", category: .strength, muscleGroups: [chest], equipment: .dumbbells, description: "An isolation exercise for developing the pectoral muscles.", instructions: ["Lie on a flat bench with a dumbbell in each hand, palms facing each other.", "Extend your arms above your chest with a slight bend in your elbows.", "Lower the dumbbells out to the sides in a wide arc, then bring them back together at the top."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .chest)
            Exercise(name: "Chest Fly", category: .strength, muscleGroups: [chest], equipment: .dumbbells, description: "An isolation exercise for developing the pectoral muscles.", instructions: ["Lie on a flat bench with a dumbbell in each hand, palms facing each other.", "Extend your arms above your chest with a slight bend in your elbows.", "Lower the dumbbells out to the sides in a wide arc, then bring them back together at the top."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .chest)
            Exercise(name: "Chin Up", category: .strength, muscleGroups: [back, .biceps], equipment: .bodyweight, description: "A bodyweight pulling exercise that targets the back and biceps.", instructions: ["Hang from a pull-up bar with an underhand grip, hands shoulder-width apart.", "Pull your body up until your chin clears the bar.", "Slowly lower your body back down to the starting position."], difficulty: .intermediate, exerciseType: .primary, targetMuscleGroup: .back)
            Exercise(name: "Concentration Curl", category: .strength, muscleGroups: [biceps], equipment: .dumbbells, description: "An isolation exercise for the biceps that minimizes momentum and focuses on peak contraction.", instructions: ["Sit on a bench with a dumbbell in one hand.", "Brace your elbow against the inside of your thigh.", "Curl the dumbbell up toward your shoulder, then slowly lower it back down."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .biceps)
            Exercise(name: "Decline Bench Press", category: .strength, muscleGroups: [chest, .triceps], equipment: .barbell, description: "A compound chest exercise that emphasizes the lower pectoral muscles.", instructions: ["Lie on a decline bench with your feet secured, gripping the barbell with a wide overhand grip.", "Lower the bar to your lower chest.", "Press the bar back up to the starting position."], difficulty: .intermediate, exerciseType: .primary, targetMuscleGroup: .chest)
            Exercise(name: "Decline Bench Press", category: .strength, muscleGroups: [chest, .triceps], equipment: .dumbbells, description: "An effective compound exercise for targeting the lower chest.", instructions: ["Lie on a decline bench with a dumbbell in each hand.", "Lower the dumbbells to the sides of your lower chest.", "Press the dumbbells up until your arms are fully extended."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .chest)
            Exercise(name: "Decline Cable Fly", category: .strength, muscleGroups: [chest], equipment: .cable, description: "An isolation exercise for the lower chest that provides continuous tension.", instructions: ["Set the pulleys high on a cable machine.", "Grasp the handles and stand in the middle, leaning forward.", "Bring your hands down and in front of your body in an arcing motion."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .chest)
            Exercise(name: "Decline Crunch", category: .strength, muscleGroups: [core], equipment: .bodyweight, description: "A core exercise performed on a decline bench to increase the range of motion and difficulty.", instructions: ["Lie on a decline bench with your feet secured.", "Place your hands behind your head or crossed over your chest.", "Crunch your upper body up, then slowly return to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .core)
            Exercise(name: "Decline Fly", category: .strength, muscleGroups: [chest], equipment: .dumbbells, description: "An isolation exercise that targets the lower pectoral muscles.", instructions: ["Lie on a decline bench with a dumbbell in each hand.", "Extend your arms above your lower chest with a slight bend in your elbows.", "Lower the dumbbells out to the sides in an arc, then bring them back together."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .chest)
            Exercise(name: "Flat Leg Raise", category: .strength, muscleGroups: [core], equipment: .bodyweight, description: "A bodyweight exercise for strengthening the lower abdominal muscles.", instructions: ["Lie on your back on the floor with your legs straight.", "Keep your lower back pressed to the floor and slowly raise your legs toward the ceiling.", "Slowly lower your legs back down without touching the floor."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .core)
            Exercise(name: "Face Pull", category: .strength, muscleGroups: [shoulders], equipment: .cable, description: "An exercise for strengthening the rear deltoids and upper back, promoting better posture.", instructions: ["Attach a rope to a high cable pulley.", "Pull the rope toward your face, externally rotating your shoulders.", "Squeeze your shoulder blades together and hold for a moment before returning."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .shoulders)
            Exercise(name: "Front Raise", category: .strength, muscleGroups: [shoulders], equipment: .cable, description: "An isolation exercise for the front deltoids that maintains tension throughout the movement.", instructions: ["Stand facing a low cable pulley with a handle.", "Raise your straight arm out in front of you until it is at shoulder height.", "Slowly lower your arm back to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .shoulders)
            Exercise(name: "Front Raise", category: .strength, muscleGroups: [shoulders], equipment: .dumbbells, description: "A shoulder exercise that isolates the front head of the deltoids.", instructions: ["Stand with a dumbbell in each hand in front of your thighs, palms facing your body.", "Raise one or both arms straight up until they are parallel to the floor.", "Slowly lower the dumbbell(s) back to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .shoulders)
            Exercise(name: "Front Raise", category: .strength, muscleGroups: [shoulders], equipment: .barbell, description: "An exercise that targets the front deltoids using a barbell.", instructions: ["Stand with your feet shoulder-width apart, holding a barbell in front of you.", "Raise the barbell up with straight arms until it is at shoulder height.", "Slowly lower the barbell back to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .shoulders)
            Exercise(name: "Goblet Squat", category: .strength, muscleGroups: [legs, .glutes], equipment: .kettlebell, description: "A beginner-friendly squat variation that improves squat form and core strength.", instructions: ["Hold a kettlebell close to your chest with both hands.", "Squat down by pushing your hips back and keeping your chest up.", "Stand back up to the starting position, squeezing your glutes."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .legs)
            Exercise(name: "Hammer Curl", category: .strength, muscleGroups: [biceps, .forearms], equipment: .cable, description: "A bicep exercise that also targets the forearms, providing constant tension.", instructions: ["Attach a rope to a low cable pulley.", "Hold the rope handles with a neutral grip (palms facing each other).", "Curl the handles up toward your shoulders, then slowly lower them back down."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .biceps)
            Exercise(name: "Hammer Curl", category: .strength, muscleGroups: [biceps, .forearms], equipment: .dumbbells, description: "A bicep and forearm exercise that is performed with a neutral grip.", instructions: ["Stand with a dumbbell in each hand, palms facing your body.", "Curl the dumbbells up toward your shoulders, keeping your palms facing each other.", "Slowly lower the dumbbells back to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .biceps)
            Exercise(name: "Hip Thrust", category: .strength, muscleGroups: [legs, .glutes], equipment: .barbell, description: "A glute exercise that is one of the most effective ways to build hip strength and size.", instructions: ["Sit on the floor with your upper back against a bench and a barbell resting on your hips.", "Drive your hips up toward the ceiling, squeezing your glutes at the top.", "Slowly lower your hips back down to the starting position."], difficulty: .intermediate, exerciseType: .primary, targetMuscleGroup: .glutes)
            Exercise(name: "Incline Bench Press", category: .strength, muscleGroups: [chest, .shoulders, .triceps], equipment: .dumbbells, description: "A compound exercise for the upper chest and shoulders.", instructions: ["Lie on an incline bench with a dumbbell in each hand.", "Press the dumbbells up from your chest to full extension.", "Slowly lower the dumbbells back down to your chest."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .chest)
            Exercise(name: "Incline Cable Fly", category: .strength, muscleGroups: [chest], equipment: .cable, description: "An isolation exercise for the upper chest that provides continuous tension.", instructions: ["Set the pulleys low on a cable machine.", "Grasp the handles and stand in the middle, leaning slightly forward.", "Raise your hands up and in front of your body in an arcing motion."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .chest)
            Exercise(name: "Incline Chest Fly", category: .strength, muscleGroups: [chest], equipment: .dumbbells, description: "An isolation exercise that targets the upper pectoral muscles.", instructions: ["Lie on an incline bench with a dumbbell in each hand.", "Extend your arms above your chest with a slight bend in your elbows.", "Lower the dumbbells out to the sides in an arc, then bring them back together."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .chest)
            Exercise(name: "Incline Curl", category: .strength, muscleGroups: [biceps], equipment: .dumbbells, description: "A bicep exercise performed on an incline bench to increase the stretch on the muscle.", instructions: ["Sit on an incline bench with a dumbbell in each hand, palms facing forward.", "Keep your elbows fixed and curl the dumbbells toward your shoulders.", "Slowly lower the dumbbells back to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .biceps)
            Exercise(name: "Incline Row", category: .strength, muscleGroups: [back, .biceps], equipment: .dumbbells, description: "A back exercise that minimizes momentum and isolates the lats.", instructions: ["Lie chest-down on an incline bench with a dumbbell in each hand.", "Pull the dumbbells up toward your chest, squeezing your shoulder blades together.", "Slowly lower the dumbbells back down to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .back)
            Exercise(name: "Inverted Row", category: .strength, muscleGroups: [back, .biceps], equipment: .bodyweight, description: "A bodyweight exercise for building back strength, often used as a progression toward pull-ups.", instructions: ["Lie on your back under a bar and grab it with an overhand grip.", "Pull your chest up toward the bar, keeping your body straight from head to heels.", "Slowly lower your body back to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .back)
            Exercise(name: "Kickbacks", category: .strength, muscleGroups: [triceps], equipment: .dumbbells, description: "An isolation exercise for targeting the triceps muscles.", instructions: ["Hold a dumbbell and hinge at your hips, keeping your back straight.", "Extend your arm back until it is fully straight.", "Slowly return the dumbbell to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .triceps)
            Exercise(name: "Knee Raise (Captain's Chair)", category: .strength, muscleGroups: [core], equipment: .machine, description: "A core exercise that targets the lower abdominal muscles using a specialized machine.", instructions: ["Step onto the captain's chair and grip the handles, pressing your back against the pad.", "Raise your knees up toward your chest, engaging your core.", "Slowly lower your legs back down to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .core)
            Exercise(name: "Landmine Calf Raises", category: .strength, muscleGroups: [calves], equipment: .barbell, description: "A variation of the calf raise that utilizes a landmine attachment to work the calves.", instructions: ["Place a barbell in a landmine attachment.", "Stand with the end of the barbell on your shoulder and perform a calf raise.", "Raise your heels up, then slowly lower them back down."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .calves)
            Exercise(name: "Landmine Chainsaw", category: .strength, muscleGroups: [back], equipment: .barbell, description: "An exercise that targets the lats and upper back in a similar fashion to a single-arm row.", instructions: ["Hinge at your hips and hold the end of a landmine barbell with one hand.", "Pull the barbell up toward your chest, squeezing your back muscles.", "Slowly lower the barbell back down."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .back)
            Exercise(name: "Landmine Chest Press", category: .strength, muscleGroups: [chest], equipment: .barbell, description: "A chest exercise that provides a unique pressing angle, reducing stress on the shoulders.", instructions: ["Hold the end of a landmine barbell in one hand at shoulder level.", "Press the barbell out in front of you until your arm is fully extended.", "Slowly return the barbell back to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .chest)
            Exercise(name: "Landmine Lateral Raises", category: .strength, muscleGroups: [shoulders], equipment: .barbell, description: "A shoulder exercise that isolates the lateral deltoid using a landmine attachment.", instructions: ["Stand sideways to a landmine attachment and hold the end of the barbell.", "Raise the barbell up and out to the side until it's at shoulder height.", "Slowly lower the barbell back down to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .shoulders)
            Exercise(name: "Landmine Lunge", category: .strength, muscleGroups: [legs, .glutes], equipment: .barbell, description: "A lunge variation that uses a landmine attachment to provide stability and a unique resistance curve.", instructions: ["Hold the end of a landmine barbell at your chest.", "Step back into a lunge, lowering your body until your back knee is just above the floor.", "Drive through your front foot to return to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .legs)
            Exercise(name: "Landmine Romanian Deadlift", category: .strength, muscleGroups: [legs, .glutes], equipment: .barbell, description: "A hamstring and glute exercise that uses a landmine attachment for a stable hip hinge.", instructions: ["Stand facing a landmine attachment and hold the end of the barbell.", "Hinge at your hips, keeping your back straight, and let the barbell lower toward the floor.", "Squeeze your glutes to return to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .legs)
            Exercise(name: "Landmine Shoulder Press", category: .strength, muscleGroups: [shoulders], equipment: .barbell, description: "A vertical pressing exercise that targets the shoulders with a safe and effective arc of motion.", instructions: ["Stand facing a landmine attachment and hold the end of the barbell at your shoulder.", "Press the barbell overhead until your arm is fully extended.", "Slowly lower the barbell back to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .shoulders)
            Exercise(name: "Landmine Squat", category: .strength, muscleGroups: [legs, .glutes], equipment: .barbell, description: "A squat variation that uses a landmine attachment to help maintain an upright torso.", instructions: ["Hold the end of a landmine barbell at your chest.", "Perform a squat, keeping your chest up and elbows in.", "Drive through your feet to stand back up to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .legs)
            Exercise(name: "Lat Pulldown", category: .strength, muscleGroups: [back, .biceps], equipment: .cable, description: "A popular back exercise that builds width and strength in the latissimus dorsi.", instructions: ["Sit at a lat pulldown machine and grip the bar with a wide overhand grip.", "Pull the bar down to your chest, squeezing your back muscles.", "Slowly let the bar rise back to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .back)
            Exercise(name: "Lat Pulldown - Underhand", category: .strength, muscleGroups: [back, .biceps], equipment: .cable, description: "A lat pulldown variation that shifts some of the focus to the biceps and lower lats.", instructions: ["Sit at a lat pulldown machine and grip the bar with an underhand grip, shoulder-width apart.", "Pull the bar down to your chest, squeezing your lats.", "Slowly let the bar rise back to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .back)
            Exercise(name: "Lat Pulldown - Wide Grip", category: .strength, muscleGroups: [back], equipment: .cable, description: "A lat pulldown variation that places maximum emphasis on the width of the lats.", instructions: ["Sit at a lat pulldown machine and grip the bar with a very wide overhand grip.", "Pull the bar down to your chest, focusing on squeezing your lats.", "Slowly let the bar rise back to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .back)
            Exercise(name: "Lateral Raise", category: .strength, muscleGroups: [shoulders], equipment: .cable, description: "An isolation exercise for the lateral deltoid that maintains constant tension.", instructions: ["Stand sideways to a low cable pulley with a handle.", "Raise your straight arm out to the side until it's at shoulder height.", "Slowly lower your arm back to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .shoulders)
            Exercise(name: "Lateral Raise", category: .strength, muscleGroups: [shoulders], equipment: .dumbbells, description: "A shoulder exercise that isolates the lateral deltoid to build shoulder width.", instructions: ["Stand with a dumbbell in each hand at your sides.", "Raise your arms straight out to the sides until they are at shoulder height.", "Slowly lower the dumbbells back to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .shoulders)
            Exercise(name: "Laying Leg Curls", category: .strength, muscleGroups: [legs], equipment: .machine, description: "A machine-based exercise that isolates the hamstrings.", instructions: ["Lie face-down on a leg curl machine with your ankles under the pad.", "Curl your legs up toward your glutes.", "Slowly lower your legs back to the starting position with control."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .legs)
            Exercise(name: "Leg Extension", category: .strength, muscleGroups: [legs], equipment: .machine, description: "A machine-based isolation exercise for the quadriceps.", instructions: ["Sit on a leg extension machine with your shins under the padded bar.", "Extend your legs until they are fully straight.", "Slowly lower your legs back to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .legs)
            Exercise(name: "Leg Press", category: .strength, muscleGroups: [legs, .glutes], equipment: .machine, description: "A compound exercise that builds strength in the legs and glutes with a reduced load on the lower back.", instructions: ["Sit in a leg press machine and place your feet on the platform.", "Lower the platform by bending your knees until they are at a 90-degree angle.", "Press the platform back up to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .legs)
            Exercise(name: "Lunge", category: .strength, muscleGroups: [legs, .glutes], equipment: .bodyweight, description: "A fundamental unilateral exercise for strengthening the legs and glutes.", instructions: ["Stand with your feet together.", "Step forward with one leg and lower your body until both knees are bent at a 90-degree angle.", "Push off your front foot to return to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .legs)
            Exercise(name: "Lunge", category: .strength, muscleGroups: [legs, .glutes], equipment: .dumbbells, description: "A weighted unilateral exercise for building leg and glute strength.", instructions: ["Hold a dumbbell in each hand and step forward with one leg.", "Lower your body until both knees are bent at a 90-degree angle.", "Push off your front foot to return to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .legs)
            Exercise(name: "Lying Leg Curl", category: .strength, muscleGroups: [legs], equipment: .machine, description: "A hamstring-focused machine exercise that isolates the back of the legs.", instructions: ["Lie face down on the machine with your ankles under the pad.", "Curl your legs up toward your glutes, squeezing your hamstrings.", "Slowly lower your legs back to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .legs)
            Exercise(name: "Overhead Press", category: .strength, muscleGroups: [shoulders, .triceps], equipment: .dumbbells, description: "A vertical pressing exercise that builds shoulder and triceps strength.", instructions: ["Stand or sit with a dumbbell in each hand at shoulder level.", "Press the dumbbells straight overhead until your arms are fully extended.", "Slowly lower the dumbbells back to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .shoulders)
            Exercise(name: "Outward Arm Swings", category: .strength, muscleGroups: [shoulders], equipment: .cable, description: "A shoulder mobility exercise that also serves as a warmup for the rotator cuff.", instructions: ["Stand sideways to a cable machine with a handle, keeping your elbow bent.", "Rotate your arm outward, away from your body.", "Slowly return to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .shoulders)
            Exercise(name: "Preacher Curl", category: .strength, muscleGroups: [biceps], equipment: .dumbbells, description: "An isolation exercise for the biceps that prevents momentum by bracing the upper arm against a pad.", instructions: ["Sit on a preacher bench and rest your upper arms on the pad.", "Hold a dumbbell in each hand, palms facing up.", "Curl the dumbbells toward your shoulders, then slowly lower them back down."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .biceps)
            Exercise(name: "Pull Up", category: .strength, muscleGroups: [back, .biceps], equipment: .bodyweight, description: "A challenging bodyweight exercise for building a strong and wide back.", instructions: ["Hang from a pull-up bar with an overhand grip, hands wider than shoulder-width.", "Pull your body up until your chin clears the bar.", "Slowly lower your body back down to the starting position."], difficulty: .intermediate, exerciseType: .primary, targetMuscleGroup: .back)
            Exercise(name: "Pullover", category: .strength, muscleGroups: [chest, .back], equipment: .dumbbells, description: "An exercise that targets the chest and lats, helping to expand the rib cage.", instructions: ["Lie perpendicular on a flat bench, holding a single dumbbell with both hands over your chest.", "Lower the dumbbell in an arc over and behind your head.", "Pull the dumbbell back up to the starting position using your chest and lats."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .chest)
            Exercise(name: "Push Up", category: .strength, muscleGroups: [chest, .triceps], equipment: .bodyweight, description: "A fundamental compound bodyweight exercise for building chest, shoulder, and triceps strength.", instructions: ["Start in a plank position with your hands slightly wider than your shoulders.", "Lower your body until your chest is just above the floor.", "Push back up to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .chest)
            Exercise(name: "Rear Lunge", category: .strength, muscleGroups: [legs, .glutes], equipment: .bodyweight, description: "A unilateral leg exercise that helps with balance and targets the glutes and legs.", instructions: ["Stand with your feet together.", "Step back with one leg and lower your body until both knees are bent at a 90-degree angle.", "Push off your back foot to return to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .legs)
            Exercise(name: "Reverse Curl", category: .strength, muscleGroups: [biceps, .forearms], equipment: .barbell, description: "A bicep and forearm exercise performed with an overhand grip.", instructions: ["Stand with your feet shoulder-width apart, holding a barbell with an overhand grip.", "Keep your elbows at your sides and curl the barbell up toward your shoulders.", "Slowly lower the barbell back to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .biceps)
            Exercise(name: "Reverse Curl", category: .strength, muscleGroups: [biceps, .forearms], equipment: .cable, description: "A bicep and forearm exercise that provides constant tension using a cable machine.", instructions: ["Attach a bar to a low cable pulley and stand facing the machine.", "Hold the bar with an overhand grip, keeping your elbows locked at your sides.", "Curl the bar up toward your shoulders, then slowly lower it back to the start."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .biceps)
            Exercise(name: "Reverse Curl", category: .strength, muscleGroups: [biceps, .forearms], equipment: .dumbbells, description: "A bicep and forearm exercise that uses a pronated grip.", instructions: ["Stand with a dumbbell in each hand, palms facing your thighs.", "Keep your elbows at your sides and curl the dumbbells up toward your shoulders.", "Slowly lower the dumbbells back to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .biceps)
            Exercise(name: "Reverse Fly", category: .strength, muscleGroups: [shoulders, .back], equipment: .dumbbells, description: "An exercise that isolates the rear deltoids and upper back to improve posture.", instructions: ["Hinge at your hips to assume a bent-over position, holding a dumbbell in each hand.", "Raise the dumbbells out to the sides until they are at shoulder height.", "Squeeze your shoulder blades together, then slowly lower the weights."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .shoulders)
            Exercise(name: "Reverse Grip Concentration Curl", category: .strength, muscleGroups: [biceps, .forearms], equipment: .dumbbells, description: "A bicep and forearm exercise that targets the brachialis muscle.", instructions: ["Sit on a bench with a dumbbell in one hand, palm facing down.", "Brace your elbow against the inside of your thigh.", "Curl the dumbbell up toward your shoulder, then slowly lower it back down."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .biceps)
            Exercise(name: "Reverse Incline Curl", category: .strength, muscleGroups: [biceps, .forearms], equipment: .dumbbells, description: "A bicep and forearm exercise performed on an incline bench with a pronated grip.", instructions: ["Sit on an incline bench with a dumbbell in each hand, palms facing down.", "Keep your elbows fixed and curl the dumbbells toward your shoulders.", "Slowly lower the dumbbells back to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .biceps)
            Exercise(name: "Romanian Deadlift", category: .strength, muscleGroups: [legs, .glutes], equipment: .dumbbells, description: "A hamstring and glute exercise that focuses on the hip hinge movement.", instructions: ["Hold a dumbbell in each hand and stand with your feet hip-width apart.", "Hinge at your hips, keeping your back straight and a slight bend in your knees.", "Lower the dumbbells toward the floor, then squeeze your glutes to return to the start."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .legs)
            Exercise(name: "Russian Twist", category: .strength, muscleGroups: [core], equipment: .bodyweight, description: "A core exercise that strengthens the obliques and improves rotational stability.", instructions: ["Sit on the floor with your knees bent and lean back slightly.", "Twist your torso from side to side, touching your hands to the floor on each side.", "Keep your core engaged throughout the movement."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .core)
            Exercise(name: "Seated Calf Raise (Plate Loaded)", category: .strength, muscleGroups: [calves], equipment: .machine, description: "A calf exercise that targets the soleus muscle with a machine.", instructions: ["Sit in the machine and place your feet on the platform, with your knees bent.", "Raise your heels up as high as possible.", "Slowly lower your heels back down to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .calves)
            Exercise(name: "Seated Overhead Press", category: .strength, muscleGroups: [shoulders, .triceps], equipment: .barbell, description: "A compound shoulder exercise performed while seated to isolate the shoulders and reduce momentum.", instructions: ["Sit on a bench with a barbell racked in front of you.", "Press the barbell overhead until your arms are fully extended.", "Slowly lower the barbell back down to your shoulders."], difficulty: .intermediate, exerciseType: .primary, targetMuscleGroup: .shoulders)
            Exercise(name: "Seated Palms Up Wrist Curl", category: .strength, muscleGroups: [forearms], equipment: .dumbbells, description: "An isolation exercise for the forearm flexors.", instructions: ["Sit on a bench with your forearms resting on your knees, palms facing up.", "Hold a dumbbell in each hand and curl your wrists upward.", "Slowly lower your wrists to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .forearms)
            Exercise(name: "Seated Row", category: .strength, muscleGroups: [back, .biceps], equipment: .cable, description: "A back exercise that builds thickness and strength in the mid-back.", instructions: ["Sit at a seated row machine with a close-grip handle.", "Pull the handle toward your abdomen, squeezing your shoulder blades together.", "Slowly let the handle return to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .back)
            Exercise(name: "Seated Wide-Grip Row", category: .strength, muscleGroups: [back], equipment: .cable, description: "A back exercise that targets the upper back and lats with a wide grip.", instructions: ["Sit at a seated row machine and grip the bar with a wide overhand grip.", "Pull the bar toward your chest, squeezing your back muscles.", "Slowly let the bar return to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .back)
            Exercise(name: "Shrug", category: .strength, muscleGroups: [back], equipment: .barbell, description: "An isolation exercise for the trapezius muscles.", instructions: ["Stand with a barbell in front of you, gripping it with an overhand grip.", "Shrug your shoulders straight up toward your ears.", "Slowly lower your shoulders back down to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .back)
            Exercise(name: "Shrug", category: .strength, muscleGroups: [back], equipment: .dumbbells, description: "An isolation exercise for the trapezius muscles using dumbbells.", instructions: ["Stand with a dumbbell in each hand at your sides.", "Shrug your shoulders straight up toward your ears.", "Slowly lower your shoulders back down to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .back)
            Exercise(name: "Side Bend", category: .strength, muscleGroups: [core], equipment: .dumbbells, description: "An exercise to strengthen the oblique muscles.", instructions: ["Stand with a dumbbell in one hand and your other hand behind your head.", "Bend sideways toward the dumbbell.", "Slowly return to the starting position, then repeat on the other side."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .core)
            Exercise(name: "Sit Up", category: .strength, muscleGroups: [core], equipment: .bodyweight, description: "A core exercise that strengthens the abdominal and hip flexor muscles.", instructions: ["Lie on your back with your knees bent and feet flat on the floor.", "Raise your upper body off the floor, bringing your torso toward your knees.", "Slowly lower your body back to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .core)
            Exercise(name: "Skullcrusher", category: .strength, muscleGroups: [triceps], equipment: .barbell, description: "A triceps isolation exercise that builds mass and strength.", instructions: ["Lie on a flat bench, holding a barbell with an overhand grip.", "Extend the barbell above your chest, then lower it toward your forehead.", "Press the barbell back up to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .triceps)
            Exercise(name: "Skullcrusher", category: .strength, muscleGroups: [triceps], equipment: .dumbbells, description: "A triceps isolation exercise that can be performed with a dumbbell in each hand.", instructions: ["Lie on a flat bench, holding a dumbbell in each hand above your chest.", "Lower the dumbbells toward your ears.", "Press the dumbbells back up to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .triceps)
            Exercise(name: "Squat", category: .strength, muscleGroups: [legs, .glutes], equipment: .bodyweight, description: "A foundational lower body exercise that builds strength and mobility.", instructions: ["Stand with your feet shoulder-width apart.", "Lower your hips down and back as if sitting in a chair.", "Drive through your feet to stand back up to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .legs)
            Exercise(name: "Squat", category: .strength, muscleGroups: [legs, .glutes], equipment: .dumbbells, description: "A weighted squat variation that strengthens the legs and glutes.", instructions: ["Hold a dumbbell in each hand at your sides.", "Lower your hips down and back as if sitting in a chair.", "Drive through your feet to stand back up to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .legs)
            Exercise(name: "Standing Calf Raise", category: .strength, muscleGroups: [calves], equipment: .barbell, description: "A calf exercise that targets the gastrocnemius muscle.", instructions: ["Stand with a barbell on your shoulders.", "Raise your heels up as high as possible.", "Slowly lower your heels back down to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .calves)
            Exercise(name: "Standing Calf Raise", category: .strength, muscleGroups: [calves], equipment: .dumbbells, description: "A calf exercise that targets the gastrocnemius muscle using dumbbells.", instructions: ["Stand holding a dumbbell in each hand.", "Raise your heels up as high as possible.", "Slowly lower your heels back down to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .calves)
            Exercise(name: "Standing Calf Raise", category: .strength, muscleGroups: [calves], equipment: .machine, description: "A machine-based calf exercise that targets the gastrocnemius muscle.", instructions: ["Stand in the machine with your shoulders under the pads.", "Raise your heels up as high as possible.", "Slowly lower your heels back down to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .calves)
            Exercise(name: "Stiff Leg Deadlift", category: .strength, muscleGroups: [legs, .glutes], equipment: .dumbbells, description: "A variation of the deadlift that focuses on the hamstrings and glutes with straight legs.", instructions: ["Stand with a dumbbell in each hand.", "Hinge at your hips, keeping your legs mostly straight and your back flat.", "Lower the dumbbells toward the floor, then squeeze your glutes to return to the start."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .legs)
            Exercise(name: "Strict Military Press", category: .strength, muscleGroups: [shoulders, .triceps], equipment: .barbell, description: "A strict overhead press that builds shoulder strength without using leg drive.", instructions: ["Stand with a barbell at your chest, feet together.", "Press the barbell straight overhead until your arms are fully extended.", "Slowly lower the barbell back down to the starting position."], difficulty: .intermediate, exerciseType: .primary, targetMuscleGroup: .shoulders)
            Exercise(name: "Superman", category: .strength, muscleGroups: [back], equipment: .bodyweight, description: "A bodyweight exercise for strengthening the lower back and glutes.", instructions: ["Lie face-down on the floor with your arms and legs extended.", "Lift your arms and legs off the floor simultaneously.", "Hold the position for a moment, then slowly lower them back down."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .back)
            Exercise(name: "T Bar Row", category: .strength, muscleGroups: [back, .biceps], equipment: .barbell, description: "A compound exercise that builds back thickness and strength using a T-bar machine or a landmine attachment.", instructions: ["Stand with your feet straddling the barbell, gripping the handles.", "Pull the weight up toward your chest, squeezing your shoulder blades together.", "Slowly lower the weight back down with control."], difficulty: .intermediate, exerciseType: .primary, targetMuscleGroup: .back)
            Exercise(name: "Triceps Dip", category: .strength, muscleGroups: [triceps], equipment: .bodyweight, description: "A bodyweight exercise for targeting the triceps muscles.", instructions: ["Grip parallel bars with your body suspended.", "Lower your body by bending your elbows until your triceps are parallel to the floor.", "Push back up to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .triceps)
            Exercise(name: "Triceps Extension", category: .strength, muscleGroups: [triceps], equipment: .cable, description: "An isolation exercise for the triceps that provides constant tension.", instructions: ["Stand facing a high cable pulley with a rope attachment.", "Extend your arms down, isolating the triceps.", "Slowly return to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .triceps)
            Exercise(name: "Triceps Extension", category: .strength, muscleGroups: [triceps], equipment: .dumbbells, description: "An isolation exercise for the triceps using a single dumbbell.", instructions: ["Sit on a bench and hold a dumbbell overhead with both hands.", "Lower the dumbbell behind your head by bending your elbows.", "Extend your arms to press the dumbbell back overhead."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .triceps)
            Exercise(name: "Triceps Pushdown", category: .strength, muscleGroups: [triceps], equipment: .cable, description: "A popular isolation exercise for the triceps that builds mass and definition.", instructions: ["Stand facing a high cable pulley with a bar attachment.", "Push the bar down, keeping your elbows locked at your sides.", "Slowly let the bar rise back to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .triceps)
            Exercise(name: "Upright Row", category: .strength, muscleGroups: [shoulders, .biceps], equipment: .cable, description: "A shoulder and bicep exercise that provides constant tension with a cable.", instructions: ["Stand facing a low cable pulley with a bar attachment.", "Pull the bar up toward your chin, leading with your elbows.", "Slowly lower the bar back down to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .shoulders)
            Exercise(name: "Upright Row", category: .strength, muscleGroups: [shoulders, .biceps], equipment: .dumbbells, description: "A shoulder and bicep exercise that targets the traps and deltoids.", instructions: ["Stand with a dumbbell in each hand in front of your thighs.", "Pull the dumbbells up toward your chin, leading with your elbows.", "Slowly lower the dumbbells back to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .shoulders)
            Exercise(name: "Upright Row", category: .strength, muscleGroups: [shoulders, .biceps], equipment: .barbell, description: "A compound exercise for the shoulders and traps using a barbell.", instructions: ["Stand with a barbell in front of your thighs, gripping it with a narrow overhand grip.", "Pull the barbell up toward your chin, leading with your elbows.", "Slowly lower the barbell back to the starting position."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .shoulders)
            Exercise(name: "Wrist Roller", category: .strength, muscleGroups: [forearms], equipment: .bodyweight, description: "An exercise for building grip and forearm strength.", instructions: ["Attach a weight to a rope with a roller handle at the top.", "Hold the handle with your arms straight out in front of you.", "Roll your wrists to wind the rope up, then slowly unwind it."], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .forearms)
            Exercise(name: "AB Workout", category: .strength, muscleGroups: [core], equipment: .bodyweight, description: "A bodyweight core exercise that strengthens the abdominal muscles.", instructions: ["Lie on your back with your knees bent and feet flat.", "Place your hands behind your head or crossed over your chest.", "Engage your core and lift your upper body off the floor, then slowly return to the start."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .core)
            Exercise(name: "Jumping Jacks", category: .cardio, muscleGroups: [legs,  .shoulders,  .core], equipment: .bodyweight, description: "A full-body dynamic warm-up exercise.", instructions: ["Stand with feet together and hands at your sides.", "Jump up while spreading your feet and bringing your hands overhead.", "Return to the starting position."], difficulty: .beginner, exerciseType: .warmup, targetMuscleGroup: .legs)
            Exercise(name: "Arm Circles", category: .flexibility, muscleGroups: [shoulders], equipment: .bodyweight, description: "A simple warm-up to increase shoulder mobility.", instructions: ["Stand with arms extended to your sides.", "Make small circles, gradually increasing the size.", "Reverse direction after 30 seconds."], difficulty: .beginner, exerciseType: .warmup, targetMuscleGroup: .shoulders)
            Exercise(name: "Quad Stretch", category: .flexibility, muscleGroups: [legs], equipment: .bodyweight, description: "A static stretch for the quadriceps.", instructions: ["Stand on one leg, holding onto something for balance if needed.", "Pull your other foot towards your glute.", "Hold for 30 seconds and switch legs."], difficulty: .beginner, exerciseType: .cooldown, targetMuscleGroup: .legs)
            Exercise(name: "Hamstring Stretch", category: .flexibility, muscleGroups: [legs], equipment: .bodyweight, description: "A static stretch for the hamstrings.", instructions: ["Sit on the floor with one extended.", "Bend the other leg so the sole of your foot touches your inner thigh.", "Reach towards your extended foot.", "Hold for 30 seconds and switch legs."], difficulty: .beginner, exerciseType: .cooldown, targetMuscleGroup: .legs)
            Exercise(name: "Push-ups", category: .strength, muscleGroups: [chest,  .triceps,  .shoulders], equipment: .bodyweight, description: "Classic bodyweight chest exercise", instructions: ["Start in a plank position with hands slightly wider than shoulders", "Lower your chest to the ground", "Push back up to starting position"], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .chest)
            Exercise(name: "Bench Press (Barbell)", category: .strength, muscleGroups: [chest,  .triceps,  .shoulders], equipment: .barbell, description: "Fundamental chest building exercise", instructions: ["Lie on bench with feet flat on floor","Grip barbell slightly wider than shoulders","Lower bar to chest, then press up"], difficulty: .intermediate, exerciseType:.primary,targetMuscleGroup: .chest)
            Exercise(name: "Incline Bench Press (Barbell)", category: .strength, muscleGroups: [chest,  .shoulders,  .triceps], equipment: .barbell, description: "Variation of the bench press that targets the upper chest.", instructions: ["Lie on an incline bench with feet flat on the floor.", "Grip the barbell slightly wider than shoulder-width apart.", "Lower the bar to your upper chest, then press it back up."], difficulty: .intermediate, exerciseType: .primary, targetMuscleGroup: .chest)
            Exercise(name: "Dumbbell Flyes", category: .strength, muscleGroups: [chest], equipment: .dumbbells, description: "Isolation exercise for chest development", instructions: ["Lie on bench holding dumbbells above chest","Lower weights in arc motion","Squeeze chest muscles to return to start"], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .chest )
            Exercise(name: "Pull-ups", category: .strength, muscleGroups: [back,  .biceps], equipment: .bodyweight, description: "Upper body pulling exercise", instructions: ["Hang from pull-up bar with palms facing away","Pull body up until chin clears bar","Lower with control"], difficulty: .intermediate, exerciseType: .primary, targetMuscleGroup: .back )
            Exercise(name: "Deadlift (Barbell)", category: .strength, muscleGroups: [back,  .legs,  .glutes], equipment: .barbell, description: "Compound full-body exercise", instructions: ["Stand with feet hip-width apart","Bend at hips and knees to grip barbell","Stand up straight, lifting the weight"], difficulty: .advanced, exerciseType: .primary, targetMuscleGroup: .back )
            Exercise(name: "Squats (Barbell)", category: .strength, muscleGroups: [legs,  .glutes], equipment: .barbell, description: "Fundamental lower body exercise", instructions: ["Stand with feet shoulder-width apart","Lower hips back and down","Return to standing position"], difficulty: .beginner, exerciseType: .primary, targetMuscleGroup: .legs )
            Exercise(name: "Front Squat (Barbell)", category: .strength, muscleGroups: [legs,  .glutes,  .core], equipment: .barbell, description: "A squat variation that places more emphasis on the quadriceps.", instructions: ["Hold the barbell across the front of your shoulders with a clean grip.","Squat down, keeping your chest up and elbows high.","Return to the starting position."], difficulty: .intermediate, exerciseType: .primary, targetMuscleGroup: .legs )
            Exercise(name: "Lunges", category: .strength, muscleGroups: [legs,  .glutes], equipment: .bodyweight, description: "Unilateral leg strengthening exercise", instructions: ["Step forward into lunge position","Lower back knee toward ground","Push back to starting position"], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .legs )
            Exercise(name: "Overhead Press (Barbell)", category: .strength, muscleGroups: [shoulders,  .triceps], equipment: .barbell, description: "A compound movement that develops shoulder strength.", instructions: ["Stand with the barbell at the front of your shoulders","Press the barbell overhead until your arms are fully extended.","Lower the barbell back to your shoulders with control."], difficulty: .intermediate, exerciseType: .primary, targetMuscleGroup: .shoulders )
            Exercise(name: "Running", category: .cardio, muscleGroups: [legs,  .core], equipment: .bodyweight, description: "Cardiovascular endurance exercise", instructions: ["Maintain steady pace","Land on midfoot","Keep relaxed posture"], difficulty: .beginner, exerciseType: .primary, targetMuscleGroup: .legs )
            Exercise(name: "Burpees", category: .cardio, muscleGroups: [chest,  .legs,  .core], equipment: .bodyweight, description: "High-intensity full body exercise", instructions: ["Start standing","Jump back to plank position","Do push-up, jump feet forward, jump up"], difficulty: .advanced, exerciseType: .primary, targetMuscleGroup: .chest )
            Exercise(name: "Plank", category: .strength, muscleGroups: [core], equipment: .bodyweight, description: "Isometric core strengthening exercise", instructions: ["Hold push-up position","Keep body straight from head to heels","Engage core muscles"], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .core )
            Exercise(name: "Bird-dog", category: .balance, muscleGroups: [core,  .glutes,  .back], equipment: .noEquipment, description: "An exercise to train the body how to stabilize the lumbar spine (low back) during upper and lower extremity movement.", instructions: ["Kneel on an exercise mat or floor", "Slowly lean forward to place your hands on the mat, positioning them directly under your shoulders at shoulder-width with your hands facing forward. Reposition your hands and knees as necessary so that your knees are directly under your hips and hands are directly under your shoulders.", "Gently stiffen your core and abdominal muscles to position your spine in a neutral position, avoiding any sagging or arching.", "Upward (Cat) Phase: Gently exhale and contract your abdominal muscles, pushing your spine upwards towards the ceiling and hold this position for 10 - 15 seconds. Allow your head to fall towards your chest, maintaining alignment with the spine.", "Downward (Cow) Phase: Slowly relax and yield to the effects of gravity. Let your stomach fall towards the floor (increasing the arch in your low back) and allow your shoulder blades to fall together (move towards the spine). Hold this position for 10 - 15 seconds before returning to your starting position"], difficulty: .intermediate, exerciseType: .accessory, targetMuscleGroup: .core )
            Exercise(name: "Cat-Cow", category: .flexibility, muscleGroups: [back,  .chest], equipment: .noEquipment, description: "A gentle exercise to warm up the spine.", instructions: ["Kneel on an exercise mat or floor, positioning your knees and feet hip-width apart, with your feet dorsi-flexed (toes pointing towards your body).", "Slowly lean forward to place your hands on the mat, positioning them directly under your shoulders at shoulder-width with your hands facing forward. Reposition your hands and knees as necessary so that your knees are directly under your hips and hands are directly under your shoulders.", "Gently stiffen your core and abdominal muscles to position your spine in a neutral position, avoiding any sagging or arching.", "Upward (Cat) Phase: Gently exhale and contract your abdominal muscles, pushing your spine upwards towards the ceiling and hold this position for 10 - 15 seconds. Allow your head to fall towards your chest, maintaining alignment with the spine.", "Downward (Cow) Phase: Slowly relax and yield to the effects of gravity. Let your stomach fall towards the floor (increasing the arch in your low back) and allow your shoulder blades to fall together (move towards the spine). Hold this position for 10 - 15 seconds before returning to your starting position"], difficulty: .beginner, exerciseType: .warmup, targetMuscleGroup: .back )
            Exercise(name: "Dumbbell Bench Press", category: .strength, muscleGroups: [chest,  .triceps,  .shoulders], equipment: .dumbbells, description: "A classic exercise for building the chest muscles.", instructions: ["Lie on a flat bench with your feet firmly on the floor. Hold a dumbbell in each hand with an overhand grip (palms facing forward).", "Position the dumbbells at the sides of your chest, with your upper arms and elbows at a 90-degree angle to your body.", "Press the dumbbells up until your arms are fully extended, but not locked. Keep the dumbbells parallel to each other.", "Slowly lower the dumbbells back to the starting position."], difficulty: .intermediate, exerciseType: .primary, targetMuscleGroup: .chest )
            Exercise(name: "Dumbbell Curl", category: .strength, muscleGroups: [biceps], equipment: .dumbbells, description: "A classic exercise for building the biceps.", instructions: ["Stand or sit with a dumbbell in each hand","Curl the weights up to shoulder level, keeping your upper arms stationary. Squeeze your biceps at the top of the movement.","Slowly lower the dumbbells back to the starting position."], difficulty: .beginner, exerciseType: .accessory, targetMuscleGroup: .biceps )

        ]
    }
    
    func getExercises(for category: Exercise.ExerciseCategory) -> [Exercise] {
        exercises.filter { $0.category == category }
    }
    
    func getExercises(for muscleGroup: Exercise.MuscleGroup) -> [Exercise] {
        exercises.filter { $0.muscleGroups.contains(muscleGroup) }
    }
    
    func searchExercises(_ query: String) -> [Exercise] {
        if query.isEmpty {
            return exercises
        }
        return exercises.filter { 
            $0.name.localizedCaseInsensitiveContains(query) ||
            $0.muscleGroups.contains { $0.rawValue.localizedCaseInsensitiveContains(query) }
        }
    }
}
